import { 
  Utensils, Car, ShoppingBag, Home, GraduationCap, 
  Gamepad2, HeartPulse, Users, Dog, Baby, 
  Smartphone, MoreHorizontal, 
} from 'lucide-react';
import { CurrencyCode, Currency } from './types';

export const CURRENCIES: Record<CurrencyCode, Currency> = {
  MYR: { code: 'MYR', symbol: 'RM', name: '马币' },
  CNY: { code: 'CNY', symbol: '¥', name: '人民币' },
  SGD: { code: 'SGD', symbol: 'S$', name: '新加坡元' },
  USD: { code: 'USD', symbol: '$', name: '美元' },
  HKD: { code: 'HKD', symbol: 'HK$', name: '港币' },
};

// Mock exchange rates relative to CNY (1 CNY = ...)
export const EXCHANGE_RATES: Record<CurrencyCode, number> = {
  CNY: 1.0,
  MYR: 0.65,
  SGD: 0.19,
  USD: 0.14,
  HKD: 1.08,
};

export const APP_VERSION = '2.4.0';

// 云同步后端地址。开发用 http://localhost:3001，生产替换为你的域名（必须 HTTPS）
export const API_BASE_URL = 'https://moneyflow.api.lixuwei.com';
// 替换为你自己的公开 version.json 地址；若留空则只检查本地 /version.json
export const GITHUB_RAW_URL = 'https://raw.githubusercontent.com/lixuwei2005-star/MoneyFlow/main/public/version.json';

export const TRANSLATIONS = {
  zh: {
    appName: 'MoneyFlow',
    totalExpense: '支出总额',
    budgetRemaining: '预算剩余',
    dailyAverage: '日均支出',
    recentTransactions: '交易记录',
    noData: '暂无数据',
    addTransaction: '记账',
    editTransaction: '编辑记录',
    amount: '支出金额',
    category: '选择分类',
    currency: '选择货币',
    note: '备注',
    save: '确定',
    delete: '删除',
    settings: '设置',
    language: '语言',
    budget: '本月预算',
    export: '导出数据',
    import: '导入数据',
    checkUpdate: '检查更新',
    autoCheckUpdate: '自动检查更新',
    autoCheckUpdateDesc: '开启后每次打开应用时会自动检查',
    theme: '主题模式',
    light: '浅色',
    dark: '深色',
    auto: '跟随系统',
    budgetCurrency: '预算币种',
    budgetUsage: '预算使用率',
    today: '今日',
    yesterday: '昨日',
    week: '本周',
    month: '本月',
    custom: '自定义',
    calendar: '日历',
    customRange: '自定义时间范围',
    presetThisYear: '本年',
    presetLastYear: '最近一年',
    presetLastMonth: '最近一月',
    presetLastWeek: '最近一周',
    startDate: '开始日期',
    endDate: '结束日期',
    shareReport: '分享报告',
    shareReportTitle: '花销情况报告',
    selectTimeRange: '选择时间范围',
    generatePdf: '生成并分享 PDF',
    generating: '正在生成...',
    noDataInRange: '该时间范围内没有记录',
    reportTotalTransactions: '记录数',
    reportTotalExpense: '总支出',
    reportCategoryBreakdown: '分类明细',
    reportTransactionList: '交易明细',
    reportGeneratedAt: '生成于',
    reportPeriod: '统计周期',
    structure: '支出结构',
    importSuccess: '导入成功',
    importError: '导入失败',
    latestVersion: '已是最新版本',
    updateFound: '发现新版本',
    updateAction: '是否立即前往下载更新？',
    updateLinkMissing: '检测到新版本，但未配置下载链接',
    updateOpenFailed: '无法打开更新链接，请稍后再试',
    general: '常规',
    clearData: '清空所有数据',
    confirmClear: '确定要清空所有数据吗？此操作不可撤销。',
    sortDefault: '默认',
    sortAmountDesc: '从大到小',
    sortAmountAsc: '从小到大',
    filterAll: '全部',
    saveSuccess: '记账成功 ✓',
    editSuccess: '修改成功 ✓',
    incompleteForm: '请填写金额和分类',
    confirmDelete: '确定要删除这条记录吗？',
  },
  en: {
    appName: 'MoneyFlow',
    totalExpense: 'Total Expense',
    budgetRemaining: 'Budget Left',
    dailyAverage: 'Daily Avg',
    recentTransactions: 'Transactions',
    noData: 'No Data',
    addTransaction: 'Add Record',
    editTransaction: 'Edit Record',
    amount: 'Amount',
    category: 'Category',
    currency: 'Currency',
    note: 'Note',
    save: 'Save',
    delete: 'Delete',
    settings: 'Settings',
    language: 'Language',
    budget: 'Monthly Budget',
    export: 'Export Data',
    import: 'Import Data',
    checkUpdate: 'Check Updates',
    autoCheckUpdate: 'Auto Check Updates',
    autoCheckUpdateDesc: 'Check for updates each time the app opens',
    theme: 'Theme Mode',
    light: 'Light',
    dark: 'Dark',
    auto: 'System',
    budgetCurrency: 'Budget Currency',
    budgetUsage: 'Budget Usage',
    today: 'Today',
    yesterday: 'Yesterday',
    week: 'Week',
    month: 'Month',
    custom: 'Custom',
    calendar: 'Calendar',
    customRange: 'Custom Range',
    presetThisYear: 'This Year',
    presetLastYear: 'Last Year',
    presetLastMonth: 'Last Month',
    presetLastWeek: 'Last Week',
    startDate: 'From',
    endDate: 'To',
    shareReport: 'Share Report',
    shareReportTitle: 'Expense Report',
    selectTimeRange: 'Select Time Range',
    generatePdf: 'Generate & Share PDF',
    generating: 'Generating...',
    noDataInRange: 'No records in this range',
    reportTotalTransactions: 'Transactions',
    reportTotalExpense: 'Total Expense',
    reportCategoryBreakdown: 'Category Breakdown',
    reportTransactionList: 'Transactions',
    reportGeneratedAt: 'Generated at',
    reportPeriod: 'Period',
    structure: 'Expense Structure',
    importSuccess: 'Imported successfully',
    importError: 'Import failed',
    latestVersion: 'Already latest version',
    updateFound: 'New version found',
    updateAction: 'Open the download page now?',
    updateLinkMissing: 'A new version is available, but no download URL is configured',
    updateOpenFailed: 'Cannot open update link. Please try again later',
    general: 'General',
    clearData: 'Clear All Data',
    confirmClear: 'Are you sure you want to clear all data? This action cannot be undone.',
    sortDefault: 'Default',
    sortAmountDesc: 'High→Low',
    sortAmountAsc: 'Low→High',
    filterAll: 'All',
    saveSuccess: 'Saved ✓',
    editSuccess: 'Updated ✓',
    incompleteForm: 'Please fill in amount and category',
    confirmDelete: 'Delete this record?',
  }
};

export interface SubCategory {
  id: string;
  name: string;
  icon?: any;
}

export interface Category {
  id: string;
  name: string;
  icon: any;
  color: string;
  subCategories: SubCategory[];
}

export const CATEGORIES: Category[] = [
  {
    id: 'dining',
    name: '餐饮',
    icon: Utensils,
    color: 'bg-orange-500',
    subCategories: [
      { id: 'breakfast', name: '早餐' },
      { id: 'lunch', name: '午餐' },
      { id: 'dinner', name: '晚餐' },
      { id: 'late_night', name: '夜宵' },
      { id: 'drinks', name: '饮料' },
      { id: 'coffee_tea', name: '咖啡奶茶' },
      { id: 'snacks', name: '零食' },
      { id: 'gathering', name: '聚餐' },
      { id: 'takeout', name: '外卖' },
      { id: 'fruit', name: '水果' },
    ],
  },
  {
    id: 'transport',
    name: '交通',
    icon: Car,
    color: 'bg-blue-500',
    subCategories: [
      { id: 'bus', name: '公交' },
      { id: 'subway', name: '地铁' },
      { id: 'taxi', name: '打车' },
      { id: 'fuel', name: '油费' },
      { id: 'parking', name: '停车费' },
      { id: 'toll', name: '过路费' },
      { id: 'train', name: '火车' },
      { id: 'high_speed_rail', name: '高铁' },
      { id: 'flight', name: '飞机' },
      { id: 'repair', name: '修车' },
      { id: 'maintenance', name: '保养' },
    ],
  },
  {
    id: 'shopping',
    name: '购物',
    icon: ShoppingBag,
    color: 'bg-pink-500',
    subCategories: [
      { id: 'daily', name: '日用品' },
      { id: 'clothes', name: '衣服' },
      { id: 'shoes', name: '鞋子' },
      { id: 'bags', name: '包包' },
      { id: 'accessories', name: '配饰' },
      { id: 'digital', name: '数码产品' },
      { id: 'home_goods', name: '家居用品' },
      { id: 'beauty', name: '美妆护肤' },
      { id: 'stationery', name: '文具' },
      { id: 'online_shopping', name: '网购' },
    ],
  },
  {
    id: 'housing',
    name: '住房',
    icon: Home,
    color: 'bg-indigo-500',
    subCategories: [
      { id: 'rent', name: '房租' },
      { id: 'water', name: '水费' },
      { id: 'electricity', name: '电费' },
      { id: 'internet', name: '网费' },
      { id: 'gas', name: '燃气费' },
      { id: 'property', name: '物业费' },
      { id: 'repair', name: '家电维修' },
      { id: 'furniture', name: '家具' },
    ],
  },
  {
    id: 'learning',
    name: '学习',
    icon: GraduationCap,
    color: 'bg-green-500',
    subCategories: [
      { id: 'books', name: '书籍' },
      { id: 'stationery', name: '文具' },
      { id: 'printing', name: '打印' },
      { id: 'courses', name: '课程' },
      { id: 'exams', name: '考试报名' },
      { id: 'software', name: '软件会员' },
      { id: 'materials', name: '学习资料' },
    ],
  },
  {
    id: 'entertainment',
    name: '娱乐',
    icon: Gamepad2,
    color: 'bg-purple-500',
    subCategories: [
      { id: 'movie', name: '电影' },
      { id: 'game', name: '游戏' },
      { id: 'ktv', name: 'KTV' },
      { id: 'travel', name: '旅游' },
      { id: 'party', name: '聚会' },
      { id: 'show', name: '演出' },
      { id: 'tickets', name: '景点门票' },
      { id: 'subscription', name: '订阅会员' },
    ],
  },
  {
    id: 'health',
    name: '医疗健康',
    icon: HeartPulse,
    color: 'bg-red-500',
    subCategories: [
      { id: 'registration', name: '挂号' },
      { id: 'medicine', name: '买药' },
      { id: 'checkup', name: '体检' },
      { id: 'dental', name: '看牙' },
      { id: 'supplements', name: '保健品' },
      { id: 'fitness', name: '健身' },
      { id: 'gear', name: '运动装备' },
    ],
  },
  {
    id: 'social',
    name: '人情社交',
    icon: Users,
    color: 'bg-yellow-600',
    subCategories: [
      { id: 'gift', name: '送礼' },
      { id: 'red_packet', name: '红包' },
      { id: 'treat', name: '请客' },
      { id: 'aa', name: '聚餐AA补差' },
      { id: 'donation', name: '捐赠' },
    ],
  },
  {
    id: 'pets',
    name: '宠物',
    icon: Dog,
    color: 'bg-amber-700',
    subCategories: [
      { id: 'food', name: '宠物粮' },
      { id: 'grooming', name: '洗护' },
      { id: 'medical', name: '医疗' },
      { id: 'toy', name: '玩具' },
      { id: 'supplies', name: '用品' },
    ],
  },
  {
    id: 'family',
    name: '家庭',
    icon: Baby,
    color: 'bg-cyan-600',
    subCategories: [
      { id: 'kids', name: '孩子开销' },
      { id: 'parents', name: '父母开销' },
      { id: 'shopping', name: '家庭采购' },
      { id: 'service', name: '家务服务' },
    ],
  },
  {
    id: 'communication',
    name: '通讯网络',
    icon: Smartphone,
    color: 'bg-slate-500',
    subCategories: [
      { id: 'phone_bill', name: '话费' },
      { id: 'plan', name: '手机套餐' },
      { id: 'broadband', name: '宽带' },
      { id: 'subscription', name: '软件订阅' },
      { id: 'cloud', name: '云服务' },
    ],
  },
  {
    id: 'others',
    name: '其他',
    icon: MoreHorizontal,
    color: 'bg-gray-500',
    subCategories: [
      { id: 'fee', name: '手续费' },
      { id: 'fine', name: '罚款' },
      { id: 'accident', name: '意外支出' },
      { id: 'misc', name: '杂项' },
    ],
  },
];
